server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      uri: http://localhost:9196
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/bookOrder
